### ISSUE TITLE
MVP #2: User Auth

### ISSUE THREAD

**Issue by fsiino** [fsiino/torino#2]
Hey Andy,

I've completed the User Authentication MVP for my FSP. I've also completed the necessary styling for the navigation. 

Feel free to let me know if anything else is needed.

Thanks,
Frankie

Live Link: <a href="https://torino-fsp.herokuapp.com/#/" target="_blank">Torino (Turo Clone)</a>
<a href="https://turo.com" target="_blank">Actual Turo</a>

### New account creation, login, & guest/demo login (07/03/2019, 2 days)
- [x] Users can sign up, sign in, log out
- [x] Users can use a demo login to try the site
- [ ] Users can't use certain features without logging in (listing or renting cars, reviews)

### Functional
No changes needed, looks great!

### Styling
- [x] change left and right padding on navbar to be 10% per side
- [x] remove padding from nav-item-wrapper containing the logo
- [x] replace navlogo div with <img> tagging. Set logo background image as the src

**Comment by minucos** [comment]
Hi Frankie

Looks great!

Just some styling changes that I think could help. I've added them as check boxes in the issue above. These are just to get a better spacing on your navbar and make it a little more responsive .

Let me know if my notes aren't clear and I'll be happy to help.

cheers

Andy

**Comment by fsiino** [comment]
Thanks Andy. I've pushed the necessary changes we discussed to prod: https://torino-fsp.herokuapp.com/#/
