### ISSUE TITLE
MVP #3: Car CRUD

### ISSUE THREAD

**Issue by fsiino** [fsiino/torino#3]
Hi Andy,

Car index, create, update & delete are now complete and deployed to heroku: https://torino-fsp.herokuapp.com/#/

Feel free to send over any feedback.

Thanks, 
Frankie
-

### 3. Cars (07/05/2019, 2 days) 

- [x] Users can add, view, edit, and remove their cars
- [x] Users can view all cars (index)

**Comment by minucos** [comment]
Looks good mate!

Happy with the functionality and styling, so I'll close this off. Good job.

Quick note, looks like your seeds might not be working for production

**Comment by fsiino** [comment]
Thanks! Seeds should be up and running now. I was experimenting in prod and didn't reseed last night. I will be adding more before tomorrow.
